apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: argocd-server
patchesStrategicMerge:
- server.yaml
